import { get, post, put } from './api-client';

export interface Message {
  id: number;
  conversationId: number;
  senderId: number;
  content: string | null;
  messageType: 'text' | 'file';
  attachmentPath: string | null;
  attachmentName: string | null;
  attachmentMime: string | null;
  attachmentSize: number | null;
  attachmentUrl?: string; // Signed URL generated by backend
  isRead: boolean;
  sentAt: string;
  sender: {
    id: number;
    role: 'candidate' | 'recruiter' | 'admin';
  };
}

export interface Conversation {
  id: number;
  candidateProfileId: number;
  recruiterProfileId: number;
  jobPostingId: number | null;
  createdAt: string;
  updatedAt: string;
  candidateProfile: {
    fullName: string;
    avatarUrl: string | null;
  };
  recruiterProfile: {
    companyName: string;
    logoUrl: string | null;
    contactName: string | null;
  };
  jobPosting: {
    title: string;
  } | null;
  messages: Message[];
  _count?: {
    messages: number;
  };
}

export interface CreateConversationPayload {
  recruiterProfileId: number;
  jobPostingId: number;
}

export const chatService = {
  async getConversations(): Promise<Conversation[]> {
    const res = await get<{ success: boolean; data: Conversation[] }>('/chat/conversations');
    return res.data;
  },

  async createConversation(payload: CreateConversationPayload): Promise<Conversation> {
    const res = await post<{ success: boolean; data: Conversation }>('/chat/conversations', payload);
    return res.data;
  },

  async getMessages(conversationId: number, page = 1, limit = 50): Promise<{ items: Message[] }> {
    const res = await get<{ success: boolean; data: Message[] }>(`/chat/conversations/${conversationId}/messages?page=${page}&limit=${limit}`);
    return { items: res.data };
  },

  async sendMessage(conversationId: number, content: string): Promise<Message> {
    const res = await post<{ success: boolean; data: Message }>(`/chat/conversations/${conversationId}/messages`, { content });
    return res.data;
  },

  async uploadAttachment(conversationId: number, file: File, content?: string): Promise<Message> {
    const formData = new FormData();
    formData.append('file', file);
    if (content) {
      formData.append('content', content);
    }
    const res = await post<{ success: boolean; data: Message }>(`/chat/conversations/${conversationId}/attachments`, formData);
    return res.data;
  },

  async markMessageRead(messageId: number): Promise<Message> {
    const res = await put<{ success: boolean; data: Message }>(`/chat/messages/${messageId}/read`);
    return res.data;
  },

  async getUnreadCount(): Promise<number> {
    const res = await get<{ success: boolean; data: { count: number } }>('/chat/conversations/unread-count');
    return res.data.count;
  },
};
