export const VIETNAM_PROVINCE_OPTIONS = [
  { label: "Hà Nội", value: "Hà Nội" },
  { label: "Huế", value: "Huế" },
  { label: "Hải Phòng", value: "Hải Phòng" },
  { label: "Đà Nẵng", value: "Đà Nẵng" },
  { label: "Thành phố Hồ Chí Minh", value: "Thành phố Hồ Chí Minh" },
  { label: "Cần Thơ", value: "Cần Thơ" },
  { label: "An Giang", value: "An Giang" },
  { label: "Bắc Ninh", value: "Bắc Ninh" },
  { label: "Cà Mau", value: "Cà Mau" },
  { label: "Cao Bằng", value: "Cao Bằng" },
  { label: "Đắk Lắk", value: "Đắk Lắk" },
  { label: "Điện Biên", value: "Điện Biên" },
  { label: "Đồng Nai", value: "Đồng Nai" },
  { label: "Đồng Tháp", value: "Đồng Tháp" },
  { label: "Gia Lai", value: "Gia Lai" },
  { label: "Hà Tĩnh", value: "Hà Tĩnh" },
  { label: "Hưng Yên", value: "Hưng Yên" },
  { label: "Khánh Hòa", value: "Khánh Hòa" },
  { label: "Lai Châu", value: "Lai Châu" },
  { label: "Lâm Đồng", value: "Lâm Đồng" },
  { label: "Lạng Sơn", value: "Lạng Sơn" },
  { label: "Lào Cai", value: "Lào Cai" },
  { label: "Nghệ An", value: "Nghệ An" },
  { label: "Ninh Bình", value: "Ninh Bình" },
  { label: "Phú Thọ", value: "Phú Thọ" },
  { label: "Quảng Ngãi", value: "Quảng Ngãi" },
  { label: "Quảng Ninh", value: "Quảng Ninh" },
  { label: "Quảng Trị", value: "Quảng Trị" },
  { label: "Sơn La", value: "Sơn La" },
  { label: "Tây Ninh", value: "Tây Ninh" },
  { label: "Thái Nguyên", value: "Thái Nguyên" },
  { label: "Thanh Hóa", value: "Thanh Hóa" },
  { label: "Tuyên Quang", value: "Tuyên Quang" },
  { label: "Vĩnh Long", value: "Vĩnh Long" },
];

export const WORK_LOCATION_OPTIONS = [
  ...VIETNAM_PROVINCE_OPTIONS,
  { label: "Remote", value: "Remote" },
  { label: "Hybrid", value: "Hybrid" },
];
